### PR TITLE
Simple theme: implement RTL

### LINKED ISSUE #747: RTL layout requires a few corrections
**How To Reproduce**

Switch to Arabic, Persian or Hebrew

**Expected behavior**

1) Preferences link should be at the left side.
2) The send search button and search form are properly placed; It's only the frame shapes that need to be Flipped Horizontally.

**Screenshots & Logs**

image

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

This PR implements the RTL text direction in the simple theme.

Modern browsers do most of the work, but margin / padding / border and some other properties have to be manage manually.

The usual method seems to be:
```css
#q {
  border-right: none;
}

#q [dir="rtl] {
  border-right: inherit;
  border-left: none;
}
```

IMO, this is error prone and require some copy / paste 

There is the [`margin-inline-start`](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-start ) property, but it seems to be supported only recently (except for FF), and it doesn't solve all cases (for example `float: right`).

So this PR uses some LESS mixins:

In LTR version:
```less
.ltr-left(@offset) {
  left: @offset;
}
```

In this RTL version:
```less
.ltr-left(@offset) {
  right: @offset;
}
```

and so on for the different CSS properties.

## Why is this change important?

Add support for RTL languages in the Simple theme.

image

## How to test this PR locally?

* check everything in a LTR language
* check everything in a RTL language

## Author's checklist

Issue list:
* [x] URL in the result
* [x] Vim hotkeys help
* [x] LTR text in the result are displayed correctly.

For the last one: I dont' know if there is a way to display LTR text aligned on the left, and RTL text aligned on the right only using CSS.

Currently, the only way I see is to [detect the text direction in Python](https://docs.python.org/3.8/library/unicodedata.html#unicodedata.bidirectional), and then add the `dir` HTML attribute.

From that, it is possible to add some CSS to display the text either aligned on the right, either aligned on the left.

ping @GreenLunar 

## Related issues

Close https://github.com/searxng/searxng/issues/747

### CODE REVIEW

File: searx/static/themes/simple/gruntfile.js [hunk 1]
```diff
@@ -117,7 +117,7 @@ module.exports = function (grunt) {
           outputSourceFiles: true,
         },
         files: {
-          "css/searxng.min.css": "src/less/style.less",
+          "css/searxng.min.css": "src/less/style-ltr.less",
```
Comment (return42) [inline searx/static/themes/simple/gruntfile.js]: I miss the `src/less/style-ltr.less` file .. or do I misunderstand this?

```
Running "less:production" (less) task
>> Destination css/searxng.min.css not written because no source files were found.
>> 1 stylesheet created.
>> 1 sourcemap created.
```
I wondering that the build `make themes.simple` ends without an error .. :confused:

Comment (dalf) [reply searx/static/themes/simple/gruntfile.js]: Face palm, I forgot to add this file. Fixed.

**Comment by mrpaulblack** [comment]
@dalf I added some small fixes on top of your branch; feel free to change/throw away/whatever :+1: 

The things that still need attention:
* about page has a `direction=ltr` on it; changing it to rtl works. but punctuation moves to the left on English text, which it should not. The solution would be a translation of that section in all RTL languages so the punctuation matches the text or to only align the text to the right without changing from LTR to RTL
* the vim help is still LTR

**Comment by dalf** [comment]
The URL are displayed left to right but aligned on the right.

Google displays each URL "part" from right to left: 
image

Bings displays the full URL from left to right (or is it broken?):
image

The Google version requires to modify [get_pretty_url](https://github.com/searxng/searxng/blob/599d882d0a43b91d6c700edb2f39a900eabbdd5c/searx/webapp.py#L420-L424) and the CSS (I'm not sure how to do that).

> the vim help is still LTR

https://github.com/searxng/searxng/issues/369 needs to be fixed first

File: searx/static/themes/simple/.stylelintrc.json [hunk 2]
```diff
@@ -1,3 +1,7 @@
 {
-  "extends": "stylelint-config-standard"
+  "extends": "stylelint-config-standard",
+  "rules": {
+    "declaration-empty-line-before": null,
+    "no-invalid-position-at-import-rule": null
+  }
```
Comment (return42) [inline searx/static/themes/simple/.stylelintrc.json:6]: IMO this should be done in a separated commit, with a commit message why we want to activate:

- https://stylelint.io/user-guide/rules/list/declaration-empty-line-before/
- https://stylelint.io/user-guide/rules/list/no-invalid-position-at-import-rule/

File: searx/static/themes/simple/src/less/style.less [hunk 3]
```diff
@@ -33,6 +33,7 @@
   vertical-align: bottom;
   line-height: 1;
   text-decoration: inherit;
+  .ltr-transform();
```
Comment (return42) [inline searx/static/themes/simple/src/less/style.less:36]: > In LTR version:

```less
.ltr-left(@offset) {
  left: @offset;
}
```

> In this RTL version:

```less
.ltr-left(@offset) {
  right: @offset;
}
```

> and so on for the different CSS properties.

Why do we choose the prefix `.ltr-` when it stands for RTL and LTR replacements, isn't it better we use a prefix like `.text-direction-` or _shorter_ `.direction-` or anything other that fits better?  .. The prefix `.rtl-` might confuse here a litle bit.

**Review by return42 — APPROVED** [review]
Except `/preferences` the RTL text orientation LGTM.

I think this PR is a huge improvement to what we have.

I left some comments with my thoughts ...

File: searx/static/themes/simple/src/less/style.less (hunk 3 above)
Comment (dalf) [reply searx/static/themes/simple/src/less/style.less:36]: My reasoning:
* We need to describe one version: either the RTL either the LTR version. From this version, the LESS mixins can create the other version.
* `.ltr-left(@offset)` means `left: @offset` in the RTL version --> when `rtl` then `left` (and adjust when `ltr`) --> `.rtl-left`.
  The idea is make clear that `left` applies to the RTL version and it has to be changed in the LTR version.

`direction-left` is telling `left` for the RTL version implicitly or it can tell `left` for LTR version and `right` in the RTL version.

File: searx/static/themes/simple/.stylelintrc.json (hunk 2 above)
Comment (dalf) [reply searx/static/themes/simple/.stylelintrc.json:6]: With `declaration-empty-line-before` enabled:
```less
#results.image-detail-open article.result-images[data-vim-selected] .detail {
  display: flex;
  flex-direction: column;
  position: fixed;
  .ltr-left(60rem);
  .ltr-right(0);
  top: @search-height;
```

has to be written
```less
#results.image-detail-open article.result-images[data-vim-selected] .detail {
  display: flex;
  flex-direction: column;
  position: fixed;

  .ltr-left(60rem);

  .ltr-right(0);
  top: @search-height;
```

---

With `no-invalid-position-at-import-rule` disabled, it allows to have these lines after the mixin declarations:
https://github.com/searxng/searxng/blob/739f0355f9f0120791f6f59ed0c5499097cf20bf/searx/static/themes/simple/src/less/style-rtl.less#L57

https://github.com/searxng/searxng/blob/739f0355f9f0120791f6f59ed0c5499097cf20bf/searx/static/themes/simple/src/less/style-rtl.less#L57

I can create a commit for this change.

Comment (return42) [reply searx/static/themes/simple/.stylelintrc.json:6]: > I can create a commit for this change.

this would be cool / thanks a lot!

Comment (dalf) [reply searx/static/themes/simple/.stylelintrc.json:6]: Done.
I've merged the other commits (I have a backup if for reason it was not a good choice).

**Review by return42 — APPROVED** [review]
I think this PR is a huge improvement to what we have.

Lets merge this PR, the `/preferences` page can be fixed in another PR.

> I have a backup if for reason it was not a good choice

from my side is no longer need for.

**Review by mrpaulblack — APPROVED** [review]
LGTM :+1: 

(We should work on making LTR text in an RTL layout to be displayed as LTR in another PR)

**Comment by GreenLunar** [comment]
Looks awesome!

**Comment by GreenLunar** [comment]
> Bings displays the full URL from left to right (or is it broken?):

In bing, it's reversed (that is, not rtl-wise)

> The URL are displayed left to right but aligned on the right.
> 
> Google displays each URL "part" from right to left: image
> 
> Bings displays the full URL from left to right (or is it broken?): image
> 
> The Google version requires to modify [get_pretty_url](https://github.com/searxng/searxng/blob/599d882d0a43b91d6c700edb2f39a900eabbdd5c/searx/webapp.py#L420-L424) and the CSS (I'm not sure how to do that).
> 
> > the vim help is still LTR
> 
> #369 needs to be fixed first

**Comment by GreenLunar** [comment]
Looks awesome!

> Bings displays the full URL from left to right (or is it broken?):

In bing, it's reversed. URL must always be LTR and NOT affected by RTL
